modLoader="javafml"
loaderVersion="[${fml_min},)"
license="GPL v3.0"

[[mods]]
modId="${modid}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="terraincognita.png"
authors="Azmalent"
description='''
Adds potion-infused snowballs..
'''

[[dependencies.potionsnowballs]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.potionsnowballs]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionsnowballs]]
    modId="inspirations"
    mandatory=false
    versionRange="[${inspirations_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionsnowballs]]
    modId="jei"
    mandatory=false
    versionRange="[${jei_version},)"
    ordering="NONE"
    side="CLIENT"